### ISSUE TITLE
[Beacon] Beacon Ranging Sounds

### ISSUE THREAD

**Issue by dpalencia** [indomie858/app-A#145]
We need an auditory cue or beep such that its frequency or intensity over the different range intervals increases, indicating that the user is getting closer ("warmer") to the beacon.

**Comment by indomie858** [comment]
Currently sounds are the same at 2.5 and 4.5 meters 
![image](https://user-images.githubusercontent.com/55901980/112249625-5ac51780-8c15-11eb-8557-3fbbab621523.png)
